### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by ssanduli** [ssanduli/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by serhii-sanduliak** [comment]
I am the oldest president of the United States to take office: I was 70 years and 239 days old on the day I took office. The previous record of 69 years and 349 days belonged to Ronald Reagan.

I've been the head and president of The Trump Organization since 1971 and the founder of the Trump Entertainment Resorts hotel and gaming chain. In 2016, my fortune was estimated at $4.5 billion .
